[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-blog_os.json" # set default target for `cargo build`

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
